Enable GitHub actions to build PDE1D + LBFGS images (#3)
* Add actions configuration

* Fix base docker build for PDEPE

* Add build requirements for pde1d

* Add pdepe script, replace ADD with COPY

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

diff --git a/Dockerfile.base b/Dockerfile.base
--- a/Dockerfile.base
+++ b/Dockerfile.base
@@ -1,22 +1,52 @@
-FROM jgoldfar/octave:base
+# FROM debian:bullseye-slim as sundials-builder
 
-LABEL maintainer="Jonathan Goldfarb <jgoldfar@my.fit.edu>"
+# LABEL maintainer="Jonathan Goldfarb <jgoldfar@gmail.com>"
+
+# # Make sure we don't get notifications we can't answer during building.
+# ENV DEBIAN_FRONTEND=noninteractive \
+#     SUNDIALS_VERSION=6.1.1
+
+# RUN apt-get -qq -y update && \
+#     apt-get -qq -y --no-install-recommends install \
+#       cmake
+
+# # Add & Install Sundials
+
+# RUN mkdir -p /sundials/build && \
+#     curl -o /tmp/sundials-${SUNDIALS_VERSION}.tar.gz -L https://computation.llnl.gov/projects/sundials/download/sundials-${SUNDIALS_VERSION}.tar.gz && \
+#     tar xzf /tmp/sundials-${SUNDIALS_VERSION}.tar.gz --directory /sundials --strip-components 1 && \
+#     cd /sundials/build && \
+#     cmake -DBLAS_ENABLE=ON -DKLU_ENABLE=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu .. && \
+#     make -j3 && make install
+
+# ## End sundials-builder image
+
+FROM debian:bullseye-slim as pde1d-builder
+
+LABEL maintainer="Jonathan Goldfarb <jgoldfar@gmail.com>"
 
 # Make sure we don't get notifications we can't answer during building.
 ENV DEBIAN_FRONTEND=noninteractive \
-    SUNDIALS_VERSION=4.1.0
+    OctaveVersion=6.4.0 \
+    USE_OCTAVE=true
 
-RUN apt-get -qq -y update && \
-    apt-get -qq -y --no-install-recommends install \
+#TODO: Re-add make check step
+# ( make check || echo "Tests Failed." )
+
+COPY ./pde1d /pde1d
+
+RUN apt-get -qq -y update \
+    && apt-get -qq -y --no-install-recommends install \
+      gcc g++ make \
       libeigen3-dev \
       libboost-dev \
-      cmake
+      liboctave-dev \
+      libsundials-dev \
+      cmake \
+    && cd /pde1d \
+    && mkdir -p build \
+    && cd build \
+    && cmake -DCMAKE_INSTALL_PREFIX=/pde1d .. \
+    && make pde1d
 
-# Add & Install Sundials
-
-RUN mkdir -p /sundials/build && \
-    curl -o /tmp/sundials-${SUNDIALS_VERSION}.tar.gz -L https://computation.llnl.gov/projects/sundials/download/sundials-${SUNDIALS_VERSION}.tar.gz && \
-    tar xzf /tmp/sundials-${SUNDIALS_VERSION}.tar.gz --directory /sundials --strip-components 1 && \
-    cd /sundials/build && \
-    cmake -DBLAS_ENABLE=ON -DKLU_ENABLE=ON -DKLU_INCLUDE_DIR=/usr/include/suitesparse -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu .. && \
-    make -j3 && make install
+# End pde1d-builder image
